- name: Create nfs share and registry pv
  hosts: bastion
  become: True
  vars_files:
    - vars/infra_vars.yml
  tasks:
    - block:
        - name: Patch registry to use NFS share
          block:
            - name: Deploy yaml config for creating registry PV
              template:
                src: templates/pv_registry.j2
                dest: "{{ workspace_directory.base_path }}/pv_registry.yaml"

            - name: Creating persistent volume for registry
              command: /usr/local/bin/oc create -f {{ workspace_directory.base_path }}/pv_registry.yaml --kubeconfig={{ workspace_directory.base_path }}/config/auth/kubeconfig

            - name: Firing registry template patch
              template:
                src: templates/patch_registry.j2
                dest: /tmp/patch_registry.sh
                mode: '0755'
              
            - name: Applying patch
              command: /tmp/patch_registry.sh

            - name: Deleting temp files
              file:
                path: /tmp/patch_registry.sh
                state: absent
      when: nfs_registry_enabled
