---
- name: Cleanup playbook
  hosts: vm_host
  vars_files:
    - vars/libvirt.yml
    - vars/infra_vars.yml
  become: true
  tasks:

    - name: Destroy cluster VM
      terraform:
        force_init: true
        project_path: "terraform/{{ item }}"
        state: absent
      loop:
        - bootstrap
        - bastion
        - loadbalancer
        - workers
        - masters

    - name: Use TF project to ensure pool and network are removed
      terraform:
        project_path: "terraform/libvirt-resources"
        variables:
          domain: "{{ domain }}"
          network_cidr: ' ["{{ libvirt.network.network_cidr }}"]'
          cluster_name: "{{ cluster_name }}"
        force_init: true
        state: absent

    - name: Delete all created paths
      file:
        path: "{{ item }}"
        state: absent
      loop: 
        - "{{ terraform_libivrt_provider_folder }}"
        - "{{ terraform_home }}"
        - "{{ gopath }}/bin/terraform-provider-libvirt"
        - /usr/bin/terraform
